In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [6]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [7]:
x1.size

6

In [8]:
x2.shape

(3, 4)

In [9]:
x3.size

60

In [10]:
x2[2, 3
]

9

In [11]:
x = np.arange(10)

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[:5]

array([0, 1, 2, 3, 4])

In [14]:
x[::2]

array([0, 2, 4, 6, 8])

In [15]:
x2

array([[2, 3, 8, 1],
       [3, 3, 3, 7],
       [0, 1, 9, 9]])

In [16]:
x2[::2, ::2]

array([[2, 8],
       [0, 9]])

In [17]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x_slice = x[::2]

In [19]:
x_slice

array([0, 2, 4, 6, 8])

In [21]:
x_slice[2] = 50

In [22]:
x

array([ 0,  1,  2,  3, 50,  5,  6,  7,  8,  9])

In [23]:
x_copy = x.copy()

In [25]:
x_copy[3] = 100

In [26]:
x_copy

array([  0,   1,   2, 100,  50,   5,   6,   7,   8,   9])

In [27]:
x

array([ 0,  1,  2,  3, 50,  5,  6,  7,  8,  9])

In [31]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
x = np.array([1, 2, 3])

In [33]:
x

array([1, 2, 3])

In [35]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [36]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [37]:
x = np.array([1, 2, 3])

In [38]:
y = np.array([3, 2, 1])

In [40]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [41]:
x = np.random.randint?

In [42]:
x = np.random.randint(10, size=(3,3))

In [43]:
x

array([[2, 0, 7],
       [5, 9, 0],
       [2, 7, 2]])

In [45]:
np.concatenate([x, x])

array([[2, 0, 7],
       [5, 9, 0],
       [2, 7, 2],
       [2, 0, 7],
       [5, 9, 0],
       [2, 7, 2]])

In [46]:
np.concatenate([x, x], axis=1)

array([[2, 0, 7, 2, 0, 7],
       [5, 9, 0, 5, 9, 0],
       [2, 7, 2, 2, 7, 2]])

In [54]:
x = np.array([1, 2, 3])
y = np.array([[4, 5, 6],
              [7, 8, 9]])

In [55]:
np.vstack([x ,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
x = np.arange(10)

In [60]:
a, b, c = np.hsplit?

In [62]:
a, b, c = np.hsplit(x, [3, 5])

In [63]:
a

array([0, 1, 2])

In [64]:
b

array([3, 4])

In [65]:
c

array([5, 6, 7, 8, 9])

In [87]:
def slow_function(arr):
    result = np.array(arr)
    for i in range(result.size):
        result[i] = result[i] ** 2
    return result

In [88]:
x = [i for i in range(10000000)]

In [89]:
%%timeit
a = slow_function(x)

14.5 s ± 153 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [90]:
y = np.array(x)

In [91]:
%timeit y ** 2

62.3 ms ± 159 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [95]:
x = np.arange(5)
y = np.empty(10)

In [96]:
np.multiply(2 ** x, 5, out=y[::2])

array([ 5., 10., 20., 40., 80.])

In [97]:
y 

array([ 5.,  0., 10.,  0., 20.,  0., 40.,  0., 80.,  0.])

In [98]:
x = np.arange(1, 6)

In [99]:
np.add.reduce(x)

15

In [101]:
y = np.eye(5)

In [112]:
y

array([[1., 0., 0., 0., 0.],
       [0., 3., 5., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
y[1, 2] = 5

In [109]:
y[1, 1] = 3

In [111]:
np.add.reduce(y, axis=1)

array([1., 8., 1., 1., 1.])

In [114]:
np.add.accumulate(y, axis=1)

array([[1., 1., 1., 1., 1.],
       [0., 3., 8., 8., 8.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

In [115]:
x = np.arange(1, 10)

In [116]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [121]:
L = np.random.random?

In [130]:
L = np.random.random(100000) * 2 + 5

In [131]:
%timeit sum(L)
%timeit L.sum()

31.7 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
281 µs ± 3.14 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
