In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])

In [6]:
b = np.array([4, 5, 6, 3, 1])

In [7]:
a + b

array([5, 7, 9, 7, 6])

In [13]:
a = np.array([1, 2, 3, 4], dtype=np.float64)

In [14]:
a

array([1., 2., 3., 4.])

In [17]:
a = np.array([[i * j for i in range(5)] for j in range(6)])

In [18]:
a

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16],
       [ 0,  5, 10, 15, 20]])

In [23]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.full((1, 5), 25)

array([[25, 25, 25, 25, 25]])

In [26]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [33]:
np.random.random((3, 3))

array([[0.96439828, 0.26572057, 0.10471487],
       [0.95244318, 0.54773896, 0.6032895 ],
       [0.89037619, 0.87070329, 0.49693769]])

In [49]:
a = np.random.random(10090000)

In [52]:
a.mean()

0.4999776769500861

In [53]:
a.std()

0.28860986846832387

In [60]:
np.random.normal?